version: "3.9"

services:
  postgresql:
    image: postgres:14.4
    container_name: postgres
    restart: always
    volumes:
      - ./postgres-data/pgdata
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: besthack
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5